server:
  name: TRIPAL
  version: v1
  port: 3002
  shutdownTimeout: 0
  logging: false
  monitoring: false
  https: false

database:
  dialect: postgres
  host: localhost
  port: 5432
  database: demo2
  user: postgres
  password: abcd1234

mongo:
  uri: mongodb://admin:12345678x%40X@10.1.0.234:27017
#  uri: mongodb://localhost:27017
  database: tripal
